name: designspace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy==1.20.2
  - pillow=7.0.0=py37hcc1f983_0
  - pip=20.0.2=py37_1
  - pip:
    - asgiref==3.2.10
    - django==3.1.1
    - sqlparse==0.3.1
    - djangorestframework
    - az.cli==0.4
    - django-allauth==0.43.0
    - django-taggit==1.3.0
    - plotly==4.14.3
    - numpy-stl==2.15.1