# Generated by Django 3.1.1 on 2020-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='3d printing', max_length=200),
            preserve_default=False,
        ),
    ]
