# Generated by Django 3.1.1 on 2020-10-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
    ]
