# Generated by Django 3.1.1 on 2020-10-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_service_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='services/3DP-tech.png'),
        ),
    ]
