# Generated by Django 3.1.1 on 2020-10-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20201008_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
    ]
