# Generated by Django 3.1.1 on 2020-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='service',
            name='reviews',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
