# Generated by Django 3.1.1 on 2021-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
