# Generated by Django 3.1.1 on 2021-04-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designspace', '0004_design_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='forked',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='design',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designspace.design'),
        ),
    ]
