# Generated by Django 3.1.1 on 2021-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designspace', '0006_auto_20210428_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='forked_from',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
