# Generated by Django 3.1.1 on 2021-05-03 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designspace', '0009_auto_20210502_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='forked_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forked_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
