# Generated by Django 3.1.1 on 2021-05-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designspace', '0011_auto_20210503_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designspace.design'),
        ),
    ]
