# Generated by Django 3.1.1 on 2021-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designspace', '0012_auto_20210503_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='forked_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
